spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql:///test
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: top.aftery.mybatis.demo.handler
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: top.aftery.mybatis.generator.model
