spring:
  datasource:
    url: jdbc:mysql:///test?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      会创建数据表
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
server:
  port: 0
info:
  app:
    author: DigitalSonic
    encoding: @project.build.sourceEncoding@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always