management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    author: DigitalSonic
    encoding: @project.build.sourceEncoding@
security:
  key-store: classpath:springbucks.p12
  key-pass: spring

waiter:
  service:
    url: https://localhost:8443