spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql:///foo
    username: root
    password: roVfLFMbACrOP7RxjcqetPHPXj1Xln56mBpWzdkM5oAtWYGNZFG2WLmIR+JH/xThJmqMWU5m4QlvT/xD21CqhA==
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${publickey}
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      filters: conn,config,stat,slf4j
publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALBJoDUBTBJSgs/3Q9A9czrd3VeE2rh4+7iJAff+yw8TU4k1MsHGwYjY1cY+B0AuwKxGOAXb9syjBx1D3T45J1MCAwEAAQ==



