spring:
  datasource:
    url: jdbc:mysql:///test?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      会创建数据表
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
