spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql:///test?useSSL=false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: top.aftery.mybatis.pagehelper.demo.handler
pagehelper:
  offset-as-page-num: true
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
