spring:
  datasource:
    url: jdbc:mysql:///geektime?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
