spring:
  datasource:
    url: jdbc:mysql:///test?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      会创建数据表
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    author: DigitalSonic
    encoding: @project.build.sourceEncoding@
server:
  port: 8443
  ssl:
    key-store: classpath:springbucks.p12
    key-store-type: PKCS12
    key-store-password: spring